# Generated by Django 4.2.7 on 2023-11-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_category_iico_id_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iico_id', models.CharField(max_length=1000, null=True, unique=True)),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
            options={
                'verbose_name': 'modifier',
                'verbose_name_plural': 'modifiers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['iico_id'], name='app_modifie_iico_id_c889ff_idx')],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='modifiers',
            field=models.ManyToManyField(to='app.modifier'),
        ),
    ]
